title: Fred's Learnings and Projects
description: Exploring Cybersecurity, Coding, AI, Projects, and Tools
baseurl: ""
url: "https://www.therealfred.ca"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap  # Add for better SEO
  - jekyll-seo-tag  # Add for better SEO
collections:
  projects:
    output: true
    permalink: /projects/:title/
  tools:
    output: true
    permalink: /tools/:title/
  learning:  # Add learning as a collection
    output: true
    permalink: /learning/:title/
show_downloads: false


