# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-mermaid
  - jekyll-include-cache
  - jekyll-seo-tag

# Mermaid settings
mermaid:
  version: "9.1.3"
  options:
    theme: neutral
    startOnLoad: true
    flowchart:
      useMaxWidth: true
      htmlLabels: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      toc_sticky: true
      mermaid: false
