// Auto-generated file - Do not edit manually
// This file is generated by scripts/fetch_repositories.py
// Last updated: 2026-01-02T09:01:49.814984

const projectsData = [
  {
    "id": 1120708655,
    "name": "underwater-sim",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/underwater-sim",
    "language": "Python",
    "stars": 1,
    "forks": 0,
    "topics": [],
    "updated": "2025-12-31",
    "homepage": null
  },
  {
    "id": 1060957810,
    "name": "Kali-VM-Setup",
    "description": "Automated setup for a Kali Linux Virtual Machine optimized for Capture The Flag (CTF) competitions.",
    "url": "https://github.com/TheRealFREDP3D/Kali-VM-Setup",
    "language": "Shell",
    "stars": 1,
    "forks": 0,
    "topics": [
      "ctf",
      "kali",
      "kali-scripts",
      "linux",
      "pentesting",
      "virtualbox-vm",
      "vmware"
    ],
    "updated": "2025-12-03",
    "homepage": "https://therealfred.ca"
  },
  {
    "id": 1052184030,
    "name": "Reverse-Engineering-Field-Manual",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/Reverse-Engineering-Field-Manual",
    "language": "Python",
    "stars": 1,
    "forks": 0,
    "topics": [],
    "updated": "2025-11-24",
    "homepage": null
  },
  {
    "id": 1089856951,
    "name": "life-sim",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/life-sim",
    "language": "Python",
    "stars": 1,
    "forks": 0,
    "topics": [],
    "updated": "2025-11-17",
    "homepage": null
  },
  {
    "id": 1042462805,
    "name": "PyBroom",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/PyBroom",
    "language": "Python",
    "stars": 1,
    "forks": 0,
    "topics": [],
    "updated": "2025-09-18",
    "homepage": null
  },
  {
    "id": 714365695,
    "name": "My-Daily-Notes",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/My-Daily-Notes",
    "language": "Other",
    "stars": 1,
    "forks": 0,
    "topics": [],
    "updated": "2025-08-21",
    "homepage": null
  },
  {
    "id": 866889944,
    "name": "github-profile-summary-card",
    "description": "GitHub Action - Profile Summary Card",
    "url": "https://github.com/TheRealFREDP3D/github-profile-summary-card",
    "language": "Other",
    "stars": 2,
    "forks": 0,
    "topics": [],
    "updated": "2026-01-02",
    "homepage": null
  },
  {
    "id": 1026053651,
    "name": "therealfredp3d.github.io",
    "description": "Learning in Public & Projects",
    "url": "https://github.com/TheRealFREDP3D/therealfredp3d.github.io",
    "language": "JavaScript",
    "stars": 2,
    "forks": 0,
    "topics": [
      "ai",
      "coding",
      "ctf",
      "personnal-website",
      "self-learning"
    ],
    "updated": "2025-12-17",
    "homepage": "https://therealfred.ca/"
  },
  {
    "id": 1102381089,
    "name": "HTB-MCP-Client",
    "description": "LLM-less Full-featured Textual-based TUI client for the HackTheBox MCP server",
    "url": "https://github.com/TheRealFREDP3D/HTB-MCP-Client",
    "language": "Python",
    "stars": 2,
    "forks": 0,
    "topics": [
      "client",
      "ctf",
      "ctf-events",
      "ctf-tools",
      "hackthebox",
      "htb",
      "htb-mcp",
      "mcp",
      "mcp-client",
      "python"
    ],
    "updated": "2025-12-15",
    "homepage": "https://github.com/therealfredp3d/HTB-MCP-Client"
  },
  {
    "id": 907157110,
    "name": "George_Was_Right",
    "description": "AI agents, powered by CrewAI, to analyze recent world events through the lens of themes from George Orwell's *1984*.",
    "url": "https://github.com/TheRealFREDP3D/George_Was_Right",
    "language": "Python",
    "stars": 2,
    "forks": 0,
    "topics": [
      "1984",
      "agents",
      "ai",
      "crewai",
      "gemini",
      "groq",
      "litellm",
      "llm",
      "ollama",
      "openai",
      "orwell",
      "project",
      "serper"
    ],
    "updated": "2025-11-27",
    "homepage": ""
  },
  {
    "id": 714362039,
    "name": "TheRealFREDP3D",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/TheRealFREDP3D",
    "language": "Other",
    "stars": 2,
    "forks": 0,
    "topics": [],
    "updated": "2025-11-09",
    "homepage": null
  },
  {
    "id": 976555025,
    "name": "Gemini-Code-Assist-PR-Poetry",
    "description": "Collection of poems that are generated and added to the \"PR Reviews\" by Gemini Code Assist and the tool I made to find these gems.",
    "url": "https://github.com/TheRealFREDP3D/Gemini-Code-Assist-PR-Poetry",
    "language": "Python",
    "stars": 2,
    "forks": 0,
    "topics": [
      "fun-project",
      "gemini",
      "personal-project",
      "poetry",
      "pull-request-bot",
      "weird-ai"
    ],
    "updated": "2025-09-27",
    "homepage": "https://github.com/TheRealFREDP3D/Gemini-Code-Assist-PR-Poetry"
  },
  {
    "id": 714363064,
    "name": "My-Diablo-Website-1996",
    "description": "Take a stroll down memory lane and witness firsthand the humble beginnings of web development. It's a testament to the journey that sparked my enduring passion for coding and learning.",
    "url": "https://github.com/TheRealFREDP3D/My-Diablo-Website-1996",
    "language": "HTML",
    "stars": 2,
    "forks": 0,
    "topics": [],
    "updated": "2025-08-21",
    "homepage": ""
  },
  {
    "id": 714364733,
    "name": "My-Writeups",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/My-Writeups",
    "language": "Python",
    "stars": 2,
    "forks": 0,
    "topics": [],
    "updated": "2025-08-21",
    "homepage": null
  },
  {
    "id": 989634101,
    "name": "CTF-TUI",
    "description": "The CTF Toolkit provides an integrated environment combining terminal operations, note-taking, AI assistance, and tool management in a single, efficient interface. Built with Python's Textual framework, it aims to enhance CTF player productivity. Working Prototype!",
    "url": "https://github.com/TheRealFREDP3D/CTF-TUI",
    "language": "Python",
    "stars": 2,
    "forks": 0,
    "topics": [
      "ctf",
      "litellm",
      "llm",
      "markdown",
      "ollama",
      "personal-project",
      "python",
      "terminal"
    ],
    "updated": "2025-08-17",
    "homepage": "https://github.com/TheRealFREDP3D/CTF-TUI"
  },
  {
    "id": 976771713,
    "name": "PullPal",
    "description": "PullPal is a Python-based command-line tool designed to fetch and archive complete GitHub pull request (PR) conversations. It captures PR details, issue comments, review comments, and reviews, allowing you to save them in either Markdown or JSON format for easy reference and analysis.",
    "url": "https://github.com/TheRealFREDP3D/PullPal",
    "language": "Python",
    "stars": 2,
    "forks": 0,
    "topics": [
      "ai-commentary",
      "ai-review",
      "fetcher",
      "personal-project",
      "pull-requests",
      "python",
      "tool"
    ],
    "updated": "2025-08-17",
    "homepage": "https://github.com/TheRealFREDP3D/PullPal"
  },
  {
    "id": 1060094473,
    "name": "BanditCLI",
    "description": "A terminal-based interface for the OverTheWire Bandit wargame, built with Python and the Textual framework.",
    "url": "https://github.com/TheRealFREDP3D/BanditCLI",
    "language": "Python",
    "stars": 3,
    "forks": 0,
    "topics": [
      "bandit",
      "cli",
      "ctf",
      "cybersecurity-education",
      "overthewire",
      "python",
      "textual"
    ],
    "updated": "2025-12-15",
    "homepage": ""
  },
  {
    "id": 779013946,
    "name": "CTF-Mix",
    "description": "Some stuff I made to facilitate my work when playing CTFs or training on platforms (HackTheBox, TryHackMe, pwn.college, WeChall, Root-Me, CryptoHack, PicoCTF, ...)",
    "url": "https://github.com/TheRealFREDP3D/CTF-Mix",
    "language": "Python",
    "stars": 3,
    "forks": 0,
    "topics": [],
    "updated": "2025-10-28",
    "homepage": null
  },
  {
    "id": 748855602,
    "name": "Coding-Exercises",
    "description": "A collection of mixed stuff I wrote during training and for fun on various platforms.  ",
    "url": "https://github.com/TheRealFREDP3D/Coding-Exercises",
    "language": "Python",
    "stars": 5,
    "forks": 0,
    "topics": [
      "bash",
      "challenges",
      "ctf",
      "exercises",
      "learning",
      "python"
    ],
    "updated": "2025-12-02",
    "homepage": ""
  },
  {
    "id": 891248393,
    "name": "Ollama-Colab-qwen2.5-coder-32b",
    "description": "No description provided",
    "url": "https://github.com/TheRealFREDP3D/Ollama-Colab-qwen2.5-coder-32b",
    "language": "Jupyter Notebook",
    "stars": 7,
    "forks": 4,
    "topics": [],
    "updated": "2025-12-24",
    "homepage": null
  }
];

// Function to get all projects
function getAllProjects() {
    return projectsData;
}

// Function to get projects sorted by stars
function getProjectsByStars() {
    return projectsData.sort((a, b) => b.stars - a.stars);
}

// Function to get projects by language
function getProjectsByLanguage(language) {
    return projectsData.filter(project => 
        project.language.toLowerCase() === language.toLowerCase()
    );
}

// Function to get projects by topic
function getProjectsByTopic(topic) {
    return projectsData.filter(project =>
        project.topics.some(t => 
            t.toLowerCase().includes(topic.toLowerCase())
        )
    );
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { projectsData, getAllProjects, getProjectsByStars, getProjectsByLanguage, getProjectsByTopic };
}
