#!/usr/bin/env python3
"""
Fetch GitHub repositories and generate projects-data.js
This script is run by GitHub Actions on every PR merge to keep the projects list updated.
"""

import requests
import json
import os
from datetime import datetime
from pathlib import Path

# Configuration
GITHUB_USERNAME = "therealfredp3d"
GITHUB_API_URL = "https://api.github.com"
OUTPUT_FILE = "blog/projects-data.js"

# Language to icon/color mapping
LANGUAGE_COLORS = {
    "Python": "#3776ab",
    "JavaScript": "#f1e05a",
    "TypeScript": "#2b7489",
    "Java": "#b07219",
    "C++": "#f34b7d",
    "C": "#555555",
    "Go": "#00add8",
    "Rust": "#ce422b",
    "Ruby": "#cc342d",
    "PHP": "#777bb4",
    "HTML": "#e34c26",
    "CSS": "#563d7c",
    "Shell": "#89e051",
    "Dockerfile": "#384d54",
    "Markdown": "#083fa1",
}

def fetch_repositories():
    """Fetch all public repositories for the user."""
    try:
        url = f"{GITHUB_API_URL}/users/{GITHUB_USERNAME}/repos"
        params = {
            "type": "owner",
            "sort": "updated",
            "direction": "desc",
            "per_page": 100
        }
        
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        
        repos = response.json()
        print(f"✓ Fetched {len(repos)} repositories from GitHub")
        return repos
    except requests.exceptions.RequestException as e:
        print(f"✗ Error fetching repositories: {e}")
        return []

def format_date(date_string):
    """Format ISO date to readable format."""
    try:
        date_obj = datetime.fromisoformat(date_string.replace('Z', '+00:00'))
        return date_obj.strftime("%Y-%m-%d")
    except:
        return date_string

def process_repositories(repos):
    """Process repositories and extract relevant data."""
    projects = []
    
    for repo in repos:
        # Skip forks if you want (optional)
        if repo.get("fork", False):
            continue
        
        project = {
            "id": repo["id"],
            "name": repo["name"],
            "description": repo["description"] or "No description provided",
            "url": repo["html_url"],
            "language": repo["language"] or "Other",
            "stars": repo["stargazers_count"],
            "forks": repo["forks_count"],
            "topics": repo.get("topics", []),
            "updated": format_date(repo["updated_at"]),
            "homepage": repo["homepage"],
        }
        projects.append(project)
    
    print(f"✓ Processed {len(projects)} repositories")
    return projects

def generate_javascript_file(projects):
    """Generate the projects-data.js file."""
    # Sort by stars (descending) and then by update date
    projects_sorted = sorted(
        projects,
        key=lambda x: (-x["stars"], x["updated"]),
        reverse=True
    )
    
    # Create JavaScript content
    js_content = """// Auto-generated file - Do not edit manually
// This file is generated by scripts/fetch_repositories.py
// Last updated: {timestamp}

const projectsData = {projects_json};

// Function to get all projects
function getAllProjects() {{
    return projectsData;
}}

// Function to get projects sorted by stars
function getProjectsByStars() {{
    return projectsData.sort((a, b) => b.stars - a.stars);
}}

// Function to get projects by language
function getProjectsByLanguage(language) {{
    return projectsData.filter(project => 
        project.language.toLowerCase() === language.toLowerCase()
    );
}}

// Function to get projects by topic
function getProjectsByTopic(topic) {{
    return projectsData.filter(project =>
        project.topics.some(t => 
            t.toLowerCase().includes(topic.toLowerCase())
        )
    );
}}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = {{ projectsData, getAllProjects, getProjectsByStars, getProjectsByLanguage, getProjectsByTopic }};
}}
""".format(
        timestamp=datetime.now().isoformat(),
        projects_json=json.dumps(projects_sorted, indent=2)
    )
    
    return js_content

def write_output_file(content):
    """Write the JavaScript file to disk."""
    try:
        # Ensure directory exists
        Path(OUTPUT_FILE).parent.mkdir(parents=True, exist_ok=True)
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✓ Generated {OUTPUT_FILE}")
        return True
    except Exception as e:
        print(f"✗ Error writing output file: {e}")
        return False

def main():
    """Main execution function."""
    print("🔄 Fetching GitHub repositories...")
    
    repos = fetch_repositories()
    if not repos:
        print("✗ No repositories found or error occurred")
        return False
    
    projects = process_repositories(repos)
    if not projects:
        print("✗ No projects to process")
        return False
    
    js_content = generate_javascript_file(projects)
    
    if write_output_file(js_content):
        print("✅ Successfully generated projects-data.js")
        return True
    else:
        print("❌ Failed to generate projects-data.js")
        return False

if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
